# Generated by Django 5.0 on 2023-12-24 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('total_budget', models.IntegerField(default=100)),
                ('players', models.ManyToManyField(related_name='squads', to='players.player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='squad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
