# Generated by Django 5.0 on 2023-12-24 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('squads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='players',
        ),
        migrations.CreateModel(
            name='SquadPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squads.squad')),
            ],
            options={
                'unique_together': {('squad', 'player')},
            },
        ),
    ]
