# Generated by Django 5.0 on 2023-12-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0002_remove_squad_players_squadplayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squad',
            old_name='user',
            new_name='user_id',
        ),
    ]
