# Generated by Django 5.0 on 2023-12-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0003_rename_user_squad_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadplayer',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squadplayer',
            name='is_vice_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squadplayer',
            name='on_bench',
            field=models.BooleanField(default=False),
        ),
    ]
