# Generated by Django 5.0 on 2023-12-25 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('squads', '0004_squadplayer_is_captain_squadplayer_is_vice_captain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squadplayer',
            old_name='player',
            new_name='player_id',
        ),
        migrations.RenameField(
            model_name='squadplayer',
            old_name='squad',
            new_name='squad_id',
        ),
        migrations.AlterUniqueTogether(
            name='squadplayer',
            unique_together={('squad_id', 'player_id')},
        ),
    ]
