# Generated by Django 5.0 on 2023-12-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0006_squadplayer_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squad',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='squadplayer',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='squadplayer',
            old_name='squad_id',
            new_name='squad',
        ),
    ]
