# Generated by Django 5.0 on 2024-01-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0009_alter_squadplayer_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SquadPlayer',
        ),
    ]
