# Generated by Django 5.0.1 on 2024-01-22 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0010_delete_squadplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='total_budget',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
