# Generated by Django 5.0.1 on 2024-01-29 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0013_squad_left_transfers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='total_budget',
            field=models.DecimalField(decimal_places=1, default=100, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
