# Generated by Django 5.0.1 on 2024-01-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_draft',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
