# Generated by Django 5.0.1 on 2024-02-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_has_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='team_admin',
            field=models.IntegerField(null=True),
        ),
    ]
