# Generated by Django 5.0 on 2024-01-01 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_rename_teamid_player_team'),
        ('squads', '0010_delete_squadplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('LD', 'Left Defender'), ('LCD', 'Left Center Defender'), ('RCD', 'Right Center Defender'), ('RD', 'Right Defender'), ('LM', 'Left Midfielder'), ('CM', 'Center Midfielder'), ('RM', 'Right Midfielder'), ('LS', 'Left Striker'), ('CS', 'Center Striker'), ('RS', 'Right Striker'), ('SGK', 'Substitute Goalkeeper'), ('SD', 'Substitute Defender'), ('SM', 'Substitute Midfielder'), ('SS', 'Substitute Striker')], max_length=255)),
                ('is_captain', models.BooleanField(default=False)),
                ('is_vice_captain', models.BooleanField(default=False)),
                ('on_bench', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squads.squad')),
            ],
            options={
                'unique_together': {('squad', 'player')},
            },
        ),
    ]
