# Generated by Django 5.0.1 on 2024-01-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameweek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweek',
            name='first_game',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gameweek',
            name='last_game',
            field=models.DateTimeField(null=True),
        ),
    ]
