# Generated by Django 5.0.1 on 2024-01-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameweek', '0003_gameweek_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameweek',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
