# Generated by Django 5.0.1 on 2024-03-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameweek', '0004_alter_gameweek_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweek',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
