# Generated by Django 5.0.1 on 2024-03-03 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameweek', '0005_gameweek_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameweek',
            options={'ordering': ['number']},
        ),
    ]
