# Generated by Django 5.0.1 on 2024-02-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_responded',
            field=models.BooleanField(default=False),
        ),
    ]
