# Generated by Django 5.0.1 on 2024-01-26 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameweek', '0001_initial'),
        ('gameweek_stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameweekstats',
            name='game_week_number',
        ),
        migrations.AddField(
            model_name='gameweekstats',
            name='gameweek',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='gameweek.gameweek'),
        ),
    ]
