# Generated by Django 5.0.1 on 2024-01-26 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameweek', '0001_initial'),
        ('gameweek_stats', '0002_remove_gameweekstats_game_week_number_and_more'),
        ('players', '0002_rename_teamid_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameweekstats',
            name='gameweek',
            field=models.ForeignKey(default=145, on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='gameweek.gameweek'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameweekstats',
            name='player',
            field=models.ForeignKey(default=355, on_delete=django.db.models.deletion.CASCADE, related_name='gameweek_stats', to='players.player'),
            preserve_default=False,
        ),
    ]
