# Generated by Django 5.0.1 on 2024-02-02 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameweek_stats', '0004_remove_gameweekstats_player_gameweekstats_is_captain_and_more'),
        ('players', '0003_player_sofascore_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameweekstats',
            name='is_captain',
        ),
        migrations.RemoveField(
            model_name='gameweekstats',
            name='is_vice_captain',
        ),
        migrations.RemoveField(
            model_name='gameweekstats',
            name='on_bench',
        ),
        migrations.RemoveField(
            model_name='gameweekstats',
            name='squad_player',
        ),
        migrations.AddField(
            model_name='gameweekstats',
            name='player',
            field=models.ForeignKey(default=255, on_delete=django.db.models.deletion.CASCADE, related_name='gameweek_stats', to='players.player'),
            preserve_default=False,
        ),
    ]
