# Generated by Django 5.0.1 on 2024-02-02 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameweek', '0004_alter_gameweek_number'),
        ('gameweek_stats', '0005_remove_gameweekstats_is_captain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweekstats',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameweekstats',
            name='gameweek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_stats', to='gameweek.gameweek'),
        ),
    ]
