# Generated by Django 5.0.1 on 2024-02-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_score',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_score',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
