# Generated by Django 5.0 on 2023-12-24 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('club', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('market_value', models.IntegerField()),
                ('image_url', models.URLField()),
                ('nationality_image_url', models.URLField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('is_injured', models.BooleanField(default=False)),
                ('is_right_foot', models.BooleanField(default=True)),
                ('teamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team')),
            ],
        ),
    ]
