# Generated by Django 5.0 on 2023-12-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='teamId',
            new_name='team',
        ),
    ]
