# Generated by Django 5.0.1 on 2024-01-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_rename_teamid_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sofascore_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
